// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayplztujgpctozgmdxqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5cGx6dHVqZ3BjdG96Z21keHF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNDUzNTMsImV4cCI6MjA3MTgyMTM1M30.bgHWFzVtx6gmMd1sXryabwy05BNBtV05HntiR-qAQz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});